name: Test Actions

on: 
  pull_request:
     branches: 
      - master
  push:
     branches: 
      - test       
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Discord notification
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK}}
