name: Test Actions

on: 
  pull_request:
     branches: 
      - master
  push:
     branches: 
      - test       
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Discord notification
      uses: Ilshidur/action-discord@master
      with:
        args: '{{ EVENT_PAYLOAD.pull_request.id }}'
      env:
        DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK}}
        DISCORD_USERNAME: Notifyer
        DISCORD_AVATAR: https://www.beahero.gg/wp-content/uploads/2019/06/nanatsu-no-taizai-anuncia-que-tendra-un-nuevo-proyecto-animado.jpg
