name: Test Actions

on: 
  pull_request:
     branches: 
      - master
#   push:
#      branches: 
#       - test       
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Discord notification
      uses: Ilshidur/action-discord@master 
      with:
        args: '/tts subnormal'
      env:
        DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK}}
        DISCORD_USERNAME: Maestro de las sobras
        DISCORD_AVATAR: https://i.pinimg.com/originals/b9/e2/3b/b9e23b3e6885bbe0e7e86a0cc1f0eea1.png
#env:
       # DISCORD_WEBHOOK: ${{secrets.ASD_WEBHOOK}}
        #DISCORD_USERNAME: ${{ EVENT_PAYLOAD.pull_request.user.login }}
       # DISCORD_AVATAR: ${{ EVENT_PAYLOAD.pull_request.user.avatar_url }}
