name: Test Actions

on: 
  pull_request:
     branches: 
      - master
  push:
     branches: 
      - test       
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Discord notification
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: https://discordapp.com/api/webhooks/693742188294570016/_W2waVlXYMM453DzN9HGulI3jMDjAkrGcT1vp_SLXQszVmbjDzdTzIqjJouWNCQQGjqz
